services:
  php:
    image: ghcr.io/eventpoints/php:main
    platform: linux/arm64
    volumes:
      - .:/app:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      # expects /app/php/docker-healthcheck.sh to ping 127.0.0.1:9000
      test: ["CMD-SHELL", "/app/php/docker-healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - database

  caddy:
    image: ghcr.io/eventpoints/caddy:main
    platform: linux/arm64
    depends_on:
      - php
    environment:
      SERVER_NAME: localhost, caddy:80
      MERCURE_PUBLIC_URL: "https://localhost/.well-known/mercure"
      MERCURE_PUBLISHER_JWT_KEY: secret
      MERCURE_SUBSCRIBER_JWT_KEY: secret
    volumes:
      - .:/app:ro        # <-- serve /app/public inside the caddy container
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  database:
    image: postgis/postgis:16-3.4
    platform: linux/amd64   # note: runs under emulation on ARM hosts; remove this if you have a multi-arch image
    environment:
      POSTGRES_DB: traderpoint
      POSTGRES_USER: root
      POSTGRES_PASSWORD: traderpoint
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:4.8.0
    ports:
      - "8000:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database

volumes:
  caddy_data:
  caddy_config:
  db-data: